Creating homepage
muqa-org/demo pull request #22
Opened 2024-07-30 11:33 UTC by kkatusic

2024-08-02 10:40 UTC, b0rza requested changes
General notes, unrelated to a single file:
- extract icon paths to a single file and reference all from there instead of typing out each time (so its eg. `src={icons.muqa}`).
- re-run prettier to revert to indentation to two spaces

2024-08-02 13:17 UTC, kkatusic commented on apps/platform/.prettierrc
> +  "tabWidth": 4,
Changed

2024-08-02 13:19 UTC, kkatusic commented on apps/platform/.prettierrc
> +
done, thx

2024-08-02 13:20 UTC, kkatusic commented on apps/platform/src/app/components/RoundStatusBox.tsx
What if they want to not to close some round phase even if endDate has been passed?

2024-08-02 13:21 UTC, kkatusic commented on apps/platform/src/app/components/footer/footer.tsx
Renamed in next commit, thx

2024-08-03 14:17 UTC, kkatusic commented on apps/platform/public/images/logo/logo-muqa.svg
I know that, @MaxSemenchuk will provide svg without background, @tomislavmamic send him logo in vectors, you have it pdf ;)

2024-08-03 14:17 UTC, kkatusic commented on apps/platform/src/app/layout.tsx
> +const dmSans = DM_Sans({ subsets: ['latin'], weight: ['400', '500', '700'] });
This has been left because I was tracking where is issue with screen sizes

2024-08-03 14:18 UTC, kkatusic commented on apps/platform/src/app/components/RoundStatusBox.tsx
Don on your suggestion, committed

2024-08-08 11:45 UTC, merged